// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqghyohwatpimsuokkfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZ2h5b2h3YXRwaW1zdW9ra2ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjYxNzYsImV4cCI6MjA1OTIwMjE3Nn0.UGUX8fBlQIYP_n8PpfaJn1mjdCah5vUZdeSBVfHZF6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);